### PR TITLE
Updated requests to utilize DonorDrive public API

### PR DESCRIPTION
**Pull request by benjaminrclayton**

### CODE REVIEW

**Comment by breadweb** [comment]
Thanks @benjaminrclayton for the suggested changes. Are the different URLs documented somewhere? The page still references the URLs the Helper is currently using: https://www.extra-life.org/index.cfm?fuseaction=cms.page&id=1353

**Comment by breadweb** [comment]
I just noticed a private message on the forums about the API update (https://github.com/DonorDrive/PublicAPI) with the current being sunset in July. I'll go ahead and make the URL changes. Thanks again!

**Comment by benjaminrclayton** [comment]
No problem!

**Comment by breadweb** [comment]
Thanks again for the help. The latest release of the Helper has the required changes.

**Pull request closed without merging**
